// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiciosEC.Models;

#nullable disable

namespace ServiciosEC.Migrations
{
    [DbContext(typeof(ECContext))]
    [Migration("20260927142435_AgregarHerenciaPersonas")]
    partial class AgregarHerenciaPersonas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiciosEC.Models.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("accion");

                    b.Property<string>("DatosAntes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("datos_antes");

                    b.Property<string>("DatosDespues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("datos_despues");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tabla");

                    b.HasKey("Id")
                        .HasName("PK__Auditori__3213E83FFDCBBAAC");

                    b.HasIndex("IdPersona");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("ServiciosEC.Models.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_compra");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<string>("DenomVendedor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("denom_vendedor");

                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("estado_id");

                    b.Property<decimal?>("Exento")
                        .HasColumnType("decimal(18, 5)")
                        .HasColumnName("exento");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal?>("Grav0")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("grav_0");

                    b.Property<decimal?>("Grav105")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("grav_10_5");

                    b.Property<decimal?>("Grav21")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("grav_21");

                    b.Property<decimal?>("Grav25")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("grav_2_5");

                    b.Property<decimal?>("Grav27")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("grav_27");

                    b.Property<decimal?>("Grav5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("grav_5");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<decimal?>("Iva")
                        .HasColumnType("decimal(18, 5)")
                        .HasColumnName("iva");

                    b.Property<decimal?>("Iva0")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("iva_0");

                    b.Property<decimal?>("Iva105")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("iva_10_5");

                    b.Property<decimal?>("Iva21")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("iva_21");

                    b.Property<decimal?>("Iva25")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("iva_2_5");

                    b.Property<decimal?>("Iva27")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("iva_27");

                    b.Property<decimal?>("Iva5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("iva_5");

                    b.Property<string>("Moneda")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("moneda");

                    b.Property<decimal?>("NetoGravado")
                        .HasColumnType("decimal(18, 5)")
                        .HasColumnName("neto_gravado");

                    b.Property<decimal?>("NoGravado")
                        .HasColumnType("decimal(18, 5)")
                        .HasColumnName("no_gravado");

                    b.Property<int>("NroDesde")
                        .HasColumnType("int")
                        .HasColumnName("nro_desde");

                    b.Property<string>("NroDocVendedor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nro_doc_vendedor");

                    b.Property<int?>("NroHasta")
                        .HasColumnType("int")
                        .HasColumnName("nro_hasta");

                    b.Property<int?>("PuntoVenta")
                        .HasColumnType("int")
                        .HasColumnName("punto_venta");

                    b.Property<int?>("TipoCambio")
                        .HasColumnType("int")
                        .HasColumnName("tipo_cambio");

                    b.Property<string>("TipoDocVendedor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_doc_vendedor");

                    b.Property<string>("TipoFact")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_fact");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18, 5)")
                        .HasColumnName("total");

                    b.HasKey("IdCompra")
                        .HasName("PK__Compras__C4BAA604464DD8E7");

                    b.HasIndex("EstadoId");

                    b.HasIndex("IdPersona");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("ServiciosEC.Models.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdEstado")
                        .HasName("PK__Estados__86989FB2DB6BFC98");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("ServiciosEC.Models.EventoAgenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TodoElDia")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("EventosAgenda");
                });

            modelBuilder.Entity("ServiciosEC.Models.Ingresosbrutos", b =>
                {
                    b.Property<int>("IdIngresosbrutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ingresosbrutos");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIngresosbrutos"));

                    b.Property<decimal?>("Aduaneras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("aduaneras");

                    b.Property<decimal?>("Alicuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("alicuota");

                    b.Property<int>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("anio");

                    b.Property<decimal>("Coeficiente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(6, 5)")
                        .HasDefaultValue(1m)
                        .HasColumnName("coeficiente");

                    b.Property<DateTime>("FechaDeclaracion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_declaracion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("GravadoJurisdiccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("gravado_jurisdiccion");

                    b.Property<decimal?>("GravadoPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("gravado_pais");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<decimal?>("ImpuestoDeterminado")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18, 5)")
                        .HasColumnName("impuesto_determinado")
                        .HasComputedColumnSql("(CONVERT([decimal](18,5),[gravado_jurisdiccion]*[alicuota]))", true);

                    b.Property<int>("JurisdiccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("jurisdiccion_id");

                    b.Property<decimal?>("Percepciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("percepciones");

                    b.Property<int>("Periodo")
                        .HasColumnType("int")
                        .HasColumnName("periodo");

                    b.Property<decimal?>("Retenciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("retenciones");

                    b.Property<decimal?>("RetencionesBancarias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("retenciones_bancarias");

                    b.Property<decimal?>("Saldo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("saldo");

                    b.HasKey("IdIngresosbrutos")
                        .HasName("PK__INGRESOS__1A12CAE131987BF6");

                    b.HasIndex("IdPersona");

                    b.HasIndex("JurisdiccionId");

                    b.ToTable("INGRESOSBRUTOS", (string)null);
                });

            modelBuilder.Entity("ServiciosEC.Models.Iva", b =>
                {
                    b.Property<int>("IdIva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdIVA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIva"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(5, 3)");

                    b.HasKey("IdIva")
                        .HasName("PK__IVA__0C143A82B0D52CCA");

                    b.ToTable("IVA", (string)null);
                });

            modelBuilder.Entity("ServiciosEC.Models.Jurisdicciones", b =>
                {
                    b.Property<int>("IdJurisdiccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_jurisdiccion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJurisdiccion"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdJurisdiccion")
                        .HasName("PK__Jurisdic__2B87043A6E7627D6");

                    b.ToTable("Jurisdicciones");
                });

            modelBuilder.Entity("ServiciosEC.Models.LibroIva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Año")
                        .HasColumnType("int");

                    b.Property<decimal?>("CreditoExento")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Credito_Exento");

                    b.Property<decimal?>("CreditoIva0")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Credito_Iva0");

                    b.Property<decimal?>("CreditoIva105")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Credito_Iva105");

                    b.Property<decimal?>("CreditoIva21")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Credito_Iva21");

                    b.Property<decimal?>("CreditoIva25")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Credito_Iva25");

                    b.Property<decimal?>("CreditoIva27")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Credito_Iva27");

                    b.Property<decimal?>("CreditoIva5")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Credito_Iva5");

                    b.Property<decimal?>("CreditoIvaOtros")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Credito_IvaOtros");

                    b.Property<decimal?>("CreditoNeto0")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Credito_Neto0");

                    b.Property<decimal?>("CreditoNeto105")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Credito_Neto105");

                    b.Property<decimal?>("CreditoNeto21")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Credito_Neto21");

                    b.Property<decimal?>("CreditoNeto25")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Credito_Neto25");

                    b.Property<decimal?>("CreditoNeto27")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Credito_Neto27");

                    b.Property<decimal?>("CreditoNeto5")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Credito_Neto5");

                    b.Property<decimal?>("CreditoNetoOtros")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Credito_NetoOtros");

                    b.Property<decimal?>("CreditoNoGravado")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Credito_NoGravado");

                    b.Property<string>("Cuit")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("DebitoExento")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Debito_Exento");

                    b.Property<decimal?>("DebitoIva0")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Debito_Iva0");

                    b.Property<decimal?>("DebitoIva105")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Debito_Iva105");

                    b.Property<decimal?>("DebitoIva21")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Debito_Iva21");

                    b.Property<decimal?>("DebitoIva25")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Debito_Iva25");

                    b.Property<decimal?>("DebitoIva27")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Debito_Iva27");

                    b.Property<decimal?>("DebitoIva5")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Debito_Iva5");

                    b.Property<decimal?>("DebitoIvaOtros")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Debito_IvaOtros");

                    b.Property<decimal?>("DebitoNeto0")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Debito_Neto0");

                    b.Property<decimal?>("DebitoNeto105")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Debito_Neto105");

                    b.Property<decimal?>("DebitoNeto21")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Debito_Neto21");

                    b.Property<decimal?>("DebitoNeto25")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Debito_Neto25");

                    b.Property<decimal?>("DebitoNeto27")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Debito_Neto27");

                    b.Property<decimal?>("DebitoNeto5")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Debito_Neto5");

                    b.Property<decimal?>("DebitoNetoOtros")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Debito_NetoOtros");

                    b.Property<decimal?>("DebitoNoGravado")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Debito_NoGravado");

                    b.Property<DateTime>("FechaDeclaracion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("GravadoCreditoFiscal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GravadoDebitoFical")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<decimal>("IvaCreditoFiscal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("IvaDebitoFiscal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("Mes")
                        .HasColumnType("int");

                    b.Property<decimal?>("PercepcionesIva")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("PercepcionesIVA");

                    b.Property<decimal?>("RestCreditoExento")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestCredito_Exento");

                    b.Property<decimal?>("RestCreditoIva0")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestCredito_Iva0");

                    b.Property<decimal?>("RestCreditoIva105")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestCredito_Iva105");

                    b.Property<decimal?>("RestCreditoIva21")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestCredito_Iva21");

                    b.Property<decimal?>("RestCreditoIva25")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestCredito_Iva25");

                    b.Property<decimal?>("RestCreditoIva27")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestCredito_Iva27");

                    b.Property<decimal?>("RestCreditoIva5")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestCredito_Iva5");

                    b.Property<decimal?>("RestCreditoIvaOtros")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestCredito_IvaOtros");

                    b.Property<decimal?>("RestCreditoNeto0")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestCredito_Neto0");

                    b.Property<decimal?>("RestCreditoNeto105")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestCredito_Neto105");

                    b.Property<decimal?>("RestCreditoNeto21")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestCredito_Neto21");

                    b.Property<decimal?>("RestCreditoNeto25")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestCredito_Neto25");

                    b.Property<decimal?>("RestCreditoNeto27")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestCredito_Neto27");

                    b.Property<decimal?>("RestCreditoNeto5")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestCredito_Neto5");

                    b.Property<decimal?>("RestCreditoNetoOtros")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestCredito_NetoOtros");

                    b.Property<decimal?>("RestCreditoNoGravado")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestCredito_NoGravado");

                    b.Property<decimal?>("RestDebitoExento")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestDebito_Exento");

                    b.Property<decimal?>("RestDebitoIva0")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestDebito_Iva0");

                    b.Property<decimal?>("RestDebitoIva105")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestDebito_Iva105");

                    b.Property<decimal?>("RestDebitoIva21")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestDebito_Iva21");

                    b.Property<decimal?>("RestDebitoIva25")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestDebito_Iva25");

                    b.Property<decimal?>("RestDebitoIva27")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestDebito_Iva27");

                    b.Property<decimal?>("RestDebitoIva5")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestDebito_Iva5");

                    b.Property<decimal?>("RestDebitoIvaOtros")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestDebito_IvaOtros");

                    b.Property<decimal?>("RestDebitoNeto0")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestDebito_Neto0");

                    b.Property<decimal?>("RestDebitoNeto105")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestDebito_Neto105");

                    b.Property<decimal?>("RestDebitoNeto21")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestDebito_Neto21");

                    b.Property<decimal?>("RestDebitoNeto25")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestDebito_Neto25");

                    b.Property<decimal?>("RestDebitoNeto27")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestDebito_Neto27");

                    b.Property<decimal?>("RestDebitoNeto5")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestDebito_Neto5");

                    b.Property<decimal?>("RestDebitoNetoOtros")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestDebito_NetoOtros");

                    b.Property<decimal?>("RestDebitoNoGravado")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RestDebito_NoGravado");

                    b.Property<decimal?>("RetencionesIva")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RetencionesIVA");

                    b.Property<decimal?>("SaldoLibreDisponibilidad")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SaldoTecnico")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("SaldoTecnicoAnterior")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SaldoTecnicoNeto")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__LibroIva__3214EC073CF982F2");

                    b.HasIndex("IdPersona");

                    b.ToTable("LibroIva", (string)null);
                });

            modelBuilder.Entity("ServiciosEC.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Discriminator")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Dni")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("estado_id");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_alta")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("telefono");

                    b.HasKey("IdPersona")
                        .HasName("PK__Personas__228148B0F120C233");

                    b.HasIndex("EstadoId");

                    b.HasIndex("RolId");

                    b.HasIndex(new[] { "Dni" }, "UQ_Personas_dni")
                        .IsUnique()
                        .HasFilter("([dni] IS NOT NULL)");

                    b.HasIndex(new[] { "Email" }, "UQ__Personas__email")
                        .IsUnique()
                        .HasFilter("([email] IS NOT NULL)");

                    b.ToTable("Personas", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ServiciosEC.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdRol")
                        .HasName("PK__Roles__6ABCB5E02351A66A");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ServiciosEC.Models.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<string>("DenomComprador")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("denom_comprador");

                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("estado_id");

                    b.Property<decimal?>("Exento")
                        .HasColumnType("decimal(18, 5)")
                        .HasColumnName("exento");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal?>("Grav0")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("grav_0");

                    b.Property<decimal?>("Grav105")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("grav_10_5");

                    b.Property<decimal?>("Grav21")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("grav_21");

                    b.Property<decimal?>("Grav25")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("grav_2_5");

                    b.Property<decimal?>("Grav27")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("grav_27");

                    b.Property<decimal?>("Grav5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("grav_5");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<decimal?>("Iva")
                        .HasColumnType("decimal(18, 5)")
                        .HasColumnName("iva");

                    b.Property<decimal?>("Iva0")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("iva_0");

                    b.Property<decimal?>("Iva105")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("iva_10_5");

                    b.Property<decimal?>("Iva21")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("iva_21");

                    b.Property<decimal?>("Iva25")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("iva_2_5");

                    b.Property<decimal?>("Iva27")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("iva_27");

                    b.Property<decimal?>("Iva5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("iva_5");

                    b.Property<string>("Moneda")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("moneda");

                    b.Property<decimal?>("NetoGravado")
                        .HasColumnType("decimal(18, 5)")
                        .HasColumnName("neto_gravado");

                    b.Property<decimal?>("NoGravado")
                        .HasColumnType("decimal(18, 5)")
                        .HasColumnName("no_gravado");

                    b.Property<int>("NroDesde")
                        .HasColumnType("int")
                        .HasColumnName("nro_desde");

                    b.Property<string>("NroDocComprador")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nro_doc_comprador");

                    b.Property<int?>("NroHasta")
                        .HasColumnType("int")
                        .HasColumnName("nro_hasta");

                    b.Property<int?>("PuntoVenta")
                        .HasColumnType("int")
                        .HasColumnName("punto_venta");

                    b.Property<int?>("TipoCambio")
                        .HasColumnType("int")
                        .HasColumnName("tipo_cambio");

                    b.Property<string>("TipoDocComprador")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_doc_comprador");

                    b.Property<string>("TipoFact")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_fact");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18, 5)")
                        .HasColumnName("total");

                    b.HasKey("IdVenta")
                        .HasName("PK__Ventas__459533BF093E752F");

                    b.HasIndex("EstadoId");

                    b.HasIndex("IdPersona");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("ServiciosEC.Models.Cliente", b =>
                {
                    b.HasBaseType("ServiciosEC.Models.Persona");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cuit");

                    b.Property<string>("DomFiscal")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dom_fiscal");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("razon_social");

                    b.HasIndex(new[] { "Cuit" }, "UQ_Clientes_CUIT")
                        .IsUnique()
                        .HasFilter("[cuit] IS NOT NULL");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("ServiciosEC.Models.Usuario", b =>
                {
                    b.HasBaseType("ServiciosEC.Models.Persona");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contrasenia");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_usuario");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("ServiciosEC.Models.Auditoria", b =>
                {
                    b.HasOne("ServiciosEC.Models.Persona", "Persona")
                        .WithMany("Auditoria")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ServiciosEC.Models.Compra", b =>
                {
                    b.HasOne("ServiciosEC.Models.Estado", "Estado")
                        .WithMany("Compras")
                        .HasForeignKey("EstadoId")
                        .IsRequired()
                        .HasConstraintName("FK__Compras__estado___3F466844");

                    b.HasOne("ServiciosEC.Models.Persona", "IdPersonaNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("FK__Compras__id_pers__403A8C7D");

                    b.Navigation("Estado");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("ServiciosEC.Models.Ingresosbrutos", b =>
                {
                    b.HasOne("ServiciosEC.Models.Persona", "IdPersonaNavigation")
                        .WithMany("Ingresosbrutos")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("FK__INGRESOSB__id_pe__07C12930");

                    b.HasOne("ServiciosEC.Models.Jurisdicciones", "Jurisdiccion")
                        .WithMany("Ingresosbrutos")
                        .HasForeignKey("JurisdiccionId")
                        .IsRequired()
                        .HasConstraintName("FK__INGRESOSB__juris__08B54D69");

                    b.Navigation("IdPersonaNavigation");

                    b.Navigation("Jurisdiccion");
                });

            modelBuilder.Entity("ServiciosEC.Models.LibroIva", b =>
                {
                    b.HasOne("ServiciosEC.Models.Persona", "IdPersonaNavigation")
                        .WithMany("LibrosIva")
                        .HasForeignKey("IdPersona")
                        .HasConstraintName("FK__LibroIva__id_per__14270015");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("ServiciosEC.Models.Persona", b =>
                {
                    b.HasOne("ServiciosEC.Models.Estado", "Estado")
                        .WithMany("Personas")
                        .HasForeignKey("EstadoId")
                        .IsRequired()
                        .HasConstraintName("FK__Personas__estado__603D47BB");

                    b.HasOne("ServiciosEC.Models.Role", "Rol")
                        .WithMany("Personas")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__Personas__rol_id__61316BF4");

                    b.Navigation("Estado");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ServiciosEC.Models.Venta", b =>
                {
                    b.HasOne("ServiciosEC.Models.Estado", "Estado")
                        .WithMany("Venta")
                        .HasForeignKey("EstadoId")
                        .IsRequired()
                        .HasConstraintName("FK__Ventas__estado_i__3A81B327");

                    b.HasOne("ServiciosEC.Models.Persona", "IdPersonaNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("FK__Ventas__id_perso__3B75D760");

                    b.Navigation("Estado");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("ServiciosEC.Models.Cliente", b =>
                {
                    b.HasOne("ServiciosEC.Models.Persona", null)
                        .WithOne()
                        .HasForeignKey("ServiciosEC.Models.Cliente", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiciosEC.Models.Usuario", b =>
                {
                    b.HasOne("ServiciosEC.Models.Persona", null)
                        .WithOne()
                        .HasForeignKey("ServiciosEC.Models.Usuario", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiciosEC.Models.Estado", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Personas");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("ServiciosEC.Models.Jurisdicciones", b =>
                {
                    b.Navigation("Ingresosbrutos");
                });

            modelBuilder.Entity("ServiciosEC.Models.Persona", b =>
                {
                    b.Navigation("Auditoria");

                    b.Navigation("Compras");

                    b.Navigation("Ingresosbrutos");

                    b.Navigation("LibrosIva");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("ServiciosEC.Models.Role", b =>
                {
                    b.Navigation("Personas");
                });
#pragma warning restore 612, 618
        }
    }
}
